1.生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列。

In [2]:
import numpy as np

In [3]:
a = np.arange(0,20,1)

In [4]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

2.呈上題，將以上數列取出偶數。

In [8]:
b = np.arange(0,20,2)

In [9]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

3.呈 1 題，將數列取出 3 的倍數。

In [11]:
c = np.arange(3,20,3)

In [12]:
c

array([ 3,  6,  9, 12, 15, 18])